# action.yml
name: 'Folder MKDir'
description: 'MkDIR Folder'
inputs:
  folder:
    description: 'folder'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.folder }}

branding:
  icon: 'upload-cloud'  
  color: 'green'
